apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:I2tS5Ffwq2+mxER4aY0iQKJLcZ0ILqBgiliq2D4Ti8XQswNHuaHz74Ez4w/UTaqt6JsaScCtsCSRmVJSQKqMNDoTPBLjsIX6lL+TiwB93wTvIhqQ/I3MgxNhiHXV3p4yArXjs8AQz/iiD6WFRSWvr3tceA0FRGaT+7r48keyhzuBvRrOZ/rl4H7818cQfa8xaNFLsJG0giahQUkpKzqUbz4oBpZnrC9zuz7wZUKI3prWrXz9r3O90sJB3AdUml7/ayXoDJcAzGg2xXrp6ZB+b7RZMXgawmF7C/0TRIw2qY2enTUfjgNgFxFwRUgkW+iq6p2VDhPKULGHQXF0T99BTQ==,iv:a//hGPcWbigf5V0UMGq9FSsOvdEveYQAd7u6TvduYB8=,tag:SXVhH+GC6NYmHIcwS9YdXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5eqfqkn7xmj3lwvv2mracqyth5t4kwacvs09ctk8znkznjtrqmqksdk5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L3JSb1ptdUZKYURTMkNV
            UWNYeXNqekprRldZczNJbE1CU2x0TElRU25RCklUOUhETWY2UkdkQVI3am5maXFI
            RDlZOSt3ZWtadkdTNWZuK2llUlQyK3cKLS0tIFplT2FwZTMxckdLbkM5bEFwVVZT
            MzAyZEdVZmR2eW5hNTc3aGlqR016S0UK7Pq3hb6pizEDn9bBlbl/GO5kuNDLQfCX
            tpWesyUcav6XUbiIrOQcWVMZXLDFQN+QSzTCTu5uBsY/pBsDZ9Xtww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T13:19:14Z"
    mac: ENC[AES256_GCM,data:jqHuuJE+9E1nvAnkIt9prvFNUzfIlphANDo6OhzZXFU5FzNKrg/JXW9Sl27Eo1y3Dg1CXYbk77guCV/Wjev5IVkiyx2mPKAfkAhIWk/SBYrH+R3q/UobJJ3Olea6HBbORz9AaI8mxBZuGm5Gin8HTAe4WByOJ1qWq8uUJ/i2iis=,iv:wr+GDxoe6oqiLpCso4f/6VI/p56Q83MLMXyjgPzYjgo=,tag:nsruKPYvrEXzGnnzgSbGDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
