apiVersion: v1
kind: Secret
metadata:
    name: dockerhub
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mLfZXYzdAVa3mweo6ePTVQDyrIkeliLQ+toyru6nLNgOJ6n/5ssDlDrivRd4xr3Vr8XyphQ+GqXzV6M1gvaHFh66SUyuS4inBLJ7bLQdRE9FxZzztD0sQRB5kLLoqgvddUnHE9ZOxk/Xjh8TYyHg4tbakO5J2/Dx12DmlO4DMLBP+C553tkOpus2hIw6+Leo9EjTzAa5mgok43eufFHTBSTVhUSgVPr8txyyLaAmzYX0li5OcP4xdYveMQ3n6aEiIeSBMzq5ZcScLNa1vNKDBOAn+Q/JXieY5ba+eev2tXZOvC7pIbQTC6uYrsypWJJHW0ndtKf85h/0Vy81prR8WgJUJNeJph/23CioRB4Bs0+Y8To+67ifEVfKHbGkKyGSV6pCCVoEOl3Pu8r+l6auV7KVmZWYdQPmWZwaQU99BJ0wmKrHGd92q2eg0ZrJoVhBzQBKkqF5O/NZgWW6sEIuFXz/TkuJu6SZsODBI8BHhYA70jYck6dZKQ==,iv:Ft02a7X6w1Rz01cK7j61eDggX0e5fILozPbwfKX5j7Y=,tag:DqXn/8TpYMUxtQ+wq8g0bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108qrl5d3rrzvut3tggr2yh3w0ujdu53hdfqu55m7htpgqukw456qx62v5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNzNuZ01xeXNlVlVnMWFI
            Rm9id3pxMGJyczJxdVU2N1RxRFFiTitnL2lFClZNUW03b0xYL1VPZ2dnNlR1ejJo
            NXk2Mi8wN3JOUWhRd2ordHBvYVo0TFEKLS0tIDl1dVVndFg5VkV1SU9RbFE3akho
            VWVUdUpCMG9BbWJnNmZJMVJBcjkzRE0KBWYgKNKw2iCpq9rE57zlxWinzieqebTc
            zFdqaqo+cEtckruBWMw4oZNksIV07r6MkA9RbBx7L9mm1DyQN5YWMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T09:10:32Z"
    mac: ENC[AES256_GCM,data:z92fgdgPXwpjVP3G6I69s2qJ2qkfTcSEmKhSNQg4ARGoLxjsXVSLdP1+SxNypurrzIObIS1TTmFPltDPiuTM0+c05ylzlYzOa8lh4ecoVRNa5WsOwFo8Tv/f0G/uoqRbARff257ofo3Cs9/CzDdLxEMksqBEGK86DQrCjAoQels=,iv:gXN9RDF0udDQnOIuisyauzom6Ayoz4PZfF8GMoR/jcA=,tag:soLvOpdgjtreS6NGxQb4PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
