apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
spec:
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      containers:
      - name: backoffice
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: backoffice-config