apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adhithia-me-ingress
  labels:
    name: adhithia-me-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: adhithia.me
    http:
      paths:
      - pathType: Prefix
        path: "/goapp"
        backend:
          service:
            name: goapp
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  type: ExternalName
  externalName: goapp.core.svc
