apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adhithia-me
  labels:
    name: adhithia-me
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: adhithia.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp
            port: 
              number: 8000
      - pathType: Prefix
        path: "/goapp"
        backend:
          service:
            name: goapp
            port: 
              number: 8000
  tls:
  - hosts:
    - adhithia.me
    secretName: letsencrypt-production-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: ExternalName
  externalName: webapp.frontend.svc
---
apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  type: ExternalName
  externalName: goapp.core.svc