apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: goapp
        image: aditirvan/goapp:12 # {"$imagepolicy": "flux-system:goapp"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8000
